   
% 4 sides
zeta(1,ix)=zeta(1,ix)+........
        (zeta(1+1,ix)+zeta(N,ix)+zeta(1,ix+1)+zeta(1,ix-1))*Ah*r_dx2*dt;
    
    zeta(N,ix)=zeta(N,ix)+........
        (zeta(1,ix)+zeta(N-1,ix)+zeta(N,ix+1)+zeta(N,ix-1))*Ah*r_dx2*dt;
    
       zeta(jy,1)=zeta(jy,1)+........
        (zeta(jy+1,1)+zeta(jy-1,1)+zeta(jy,1+1)+zeta(jy,N))*Ah*r_dx2*dt;
    
     zeta(jy,N)=zeta(jy,N)+........
        (zeta(jy+1,N)+zeta(jy-1,N)+zeta(jy,1)+zeta(jy,N-1))*Ah*r_dx2*dt;
    
    
    
%     4 corners
     zeta(N,N)=zeta(N,N)+........
        (zeta(1,N)+zeta(N-1,N)+zeta(N,1)+zeta(N,N-1))*Ah*r_dx2*dt;
      zeta(1,1)=zeta(1,1)+........
        (zeta(2,1)+zeta(N,1)+zeta(1,2)+zeta(1,N))*Ah*r_dx2*dt;
     zeta(1,N)=zeta(1,N)+........
        (zeta(2,N)+zeta(N,N)+zeta(1,N-1)+zeta(1,1))*Ah*r_dx2*dt;
     zeta(N,1)=zeta(N,1)+........
        (zeta(1,1)+zeta(N-1,1)+zeta(N,N)+zeta(N,2))*Ah*r_dx2*dt;